# Generated by Django 4.2.4 on 2023-09-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_estudiantes_profesores'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='profesion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
